### ISSUE TITLE
Unable to import serial

### ISSUE THREAD

**Issue by anirjoshi** [pololu/micropython-build#1]
I am trying to use [serial](https://www.pololu.com/docs/0J73/15.7) package, but unable to import it on the robot.

**Comment by DavidEGrayson** [comment]
pySerial is not part of MicroPython; it is a library for the official Python.

MicroPython provides this class you can use:
https://docs.micropython.org/en/latest/library/machine.UART.html

We use these issues to keep track of bugs or feature requests for the micropython-build project.  For general help with using a Pololu robot, posting on our [forum](https://forum.pololu.com/) would be better.
